name: flutter_wallet_app_lesson56
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_translate: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/i18n/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
    - family: Abys
      fonts:
        - asset: assets/fonts/AbyssinicaSIL-Regular.ttf
